name: DiscordWebhookCICD
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
  pull_request:
    branches: [ master ]
  release:
    types:
      - created
      - edited

jobs:
  testDiscordActionJob:
    runs-on: ubuntu-latest
    name: A job to test out the discord github hook action
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm i

      - name: Run unit tests
        run: npm test

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-artifact
          path: coverage

      - name: Test Step for Discord Action
        id: discordAction
        uses: Poss111/discord-hook-action@v1.6.12
        with:
          discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: 'Sample Title'
          message: 'Sample Message'
          message-color: '65345'
      - name: Was Job Successful
        run: echo "The job was successful ran > ${{ steps.discordAction.outputs.successful }}"
